title: Alexander Zhang
description: Alexander Zhang's catalog of (mostly) finished projects
bio: <b>Alexander Zhang</b> is a University of Michigan student with an interest in computer science and a penchant for independent projects. He enjoys programming as a way to explore new ideas, solve everyday problems, or just have fun. Currently, he's most experienced in data analysis, robotics, and backend web development - but he's always itching to try new things. His (mostly) finished projects are cataloged below.
links:
- url: resume.html
  title: Resume
- url: https://github.com/CQCumbers
  title: Github Profile
sass:
  style: compressed
