title: Alexander Zhang
description: A collection of interesting-ish projects by Alexander Zhang
bio: I like making cool stuff and learning new technologies on the way. I guess this an obligatory online catalog and notebook of the small projects I have created with machine learning, augmented reality, web technologies, and anything else I find interesting.
links:
    - url: https://github.com/CQCumbers
      title: Github Profile
