title: Alexander Zhang
description: An online catalog of (mostly) finished projects by Alexander Zhang / Tyrese / CQCumbers
bio: <b>Alexander Zhang</b> (a.k.a. Tyrese a.k.a. CQCumbers) is a student with an interest in computer science and a penchant for independent projects. He enjoys creating many small projects for fun, or for learning new things like deep learning and augmented reality. Currently, he is most experienced in data analysis, cloud computing, and web development, though he's done robotics and desktop/mobile app development as well. This webpage serves as an online catalog of his (mostly) finished projects.
links:
- url: https://github.com/CQCumbers
  title: Github Profile
sass:
  style: compressed
