base_url = "https://cqcumbers.com"
title = "Alexander Zhang"
description = "Alexander Zhang's catalog of (mostly) finished projects"

compile_sass = true
minify_html = true
build_search_index = false

[markdown]
highlight_code = false
